name: Sync from GitLab to GitHub

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Clone GitLab repository
        run: |
          git clone --mirror https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_REPO }} gitlab-mirror
          cd gitlab-mirror
          git remote remove origin
          git remote add origin https://your-github-username:${{ secrets.GH_PAT }}@github.com/your-github-username/your-repo.git

      - name: Push to GitHub
        run: |
          cd gitlab-mirror
          git push --mirror
